package br.com.davidbuzatto.jjudge.gui;

import br.com.davidbuzatto.jjudge.utils.Utils;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class ConfigureTestDependenciesDialog extends javax.swing.JDialog {

    private List<File> javaClasspathFiles;
    private DefaultListModel<File> listDependenciesModel;
    
    private ResourceBundle bundle = Utils.bundle;
    
    /**
     * Creates new form ConfigureTestDependenciesDialog
     */
    public ConfigureTestDependenciesDialog( java.awt.Frame parent, boolean modal, List<File> javaClasspathFiles ) {
        
        super( parent, modal );
        initComponents();
        
        this.javaClasspathFiles = javaClasspathFiles;
        this.listDependenciesModel = new DefaultListModel<>();
        this.listDependencies.setModel( listDependenciesModel );
        buildListDependenciesModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDependencies = new javax.swing.JPanel();
        scrollDependencies = new javax.swing.JScrollPane();
        listDependencies = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/davidbuzatto/jjudge/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("ConfigureTestDependenciesDialog.title")); // NOI18N

        panelDependencies.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ConfigureTestDependenciesDialog.panelDependencies.border.title"))); // NOI18N

        listDependencies.setModel(new DefaultListModel<File>());
        listDependencies.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                listDependenciesKeyReleased(evt);
            }
        });
        scrollDependencies.setViewportView(listDependencies);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/add.png"))); // NOI18N
        btnAdd.setText(bundle.getString("ConfigureTestDependenciesDialog.btnAdd.text")); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/delete.png"))); // NOI18N
        btnRemove.setText(bundle.getString("ConfigureTestDependenciesDialog.btnRemove.text")); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDependenciesLayout = new javax.swing.GroupLayout(panelDependencies);
        panelDependencies.setLayout(panelDependenciesLayout);
        panelDependenciesLayout.setHorizontalGroup(
            panelDependenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDependenciesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDependenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollDependencies, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDependenciesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemove)))
                .addContainerGap())
        );
        panelDependenciesLayout.setVerticalGroup(
            panelDependenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDependenciesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollDependencies, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDependenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd))
                .addContainerGap())
        );

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/accept.png"))); // NOI18N
        btnOk.setText(bundle.getString("ConfigureTestDependenciesDialog.btnOk.text")); // NOI18N
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/stop.png"))); // NOI18N
        btnCancel.setText(bundle.getString("ConfigureTestDependenciesDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDependencies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDependencies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        JFileChooser jfc = new JFileChooser( new File( Utils.getPref( Utils.PREF_TEST_DEPENDENCIES_PATH ) ) );
        jfc.setDialogTitle( bundle.getString( "ConfigureTestDependenciesDialog.btnAddActionPerformed.jarOrDirectory" ) );
        jfc.setMultiSelectionEnabled( true );
        jfc.setFileSelectionMode( JFileChooser.FILES_AND_DIRECTORIES );
        jfc.removeChoosableFileFilter( jfc.getFileFilter() );
        jfc.setFileFilter( new FileNameExtensionFilter( 
                bundle.getString( "ConfigureTestDependenciesDialog.btnAddActionPerformed.fileTypes" ), 
                "jar" ) );
        
        if ( jfc.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION ) {
            
            File[] files = jfc.getSelectedFiles();
            
            if ( files != null && files.length > 0 ) {
                
                Utils.setPref( Utils.PREF_TEST_DEPENDENCIES_PATH, files[0].getParentFile().getAbsolutePath() );
                
                for ( File f : files ) {
                    listDependenciesModel.addElement( f );
                }
                
            }
            
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        removeJarOrDirectory();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        
        javaClasspathFiles.clear();
        
        for ( int i = 0; i < listDependenciesModel.size(); i++ ) {
            javaClasspathFiles.add( listDependenciesModel.get( i ) );
        }
        
        Utils.setPref( Utils.PREF_JAVA_CLASSPATH_DEPENDENCIES_PATHS, 
                Utils.generateFilePathsToStore( javaClasspathFiles ) );
        
        dispose();
        
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void listDependenciesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listDependenciesKeyReleased
        if ( evt.getKeyCode() == KeyEvent.VK_DELETE ) {
            removeJarOrDirectory();
        }
    }//GEN-LAST:event_listDependenciesKeyReleased

    private void buildListDependenciesModel() {
        for ( File f : javaClasspathFiles ) {
            listDependenciesModel.addElement( f );
        }
    }
    
    private void removeJarOrDirectory() {
        
        if ( listDependencies.getSelectedValue() != null ) {
            
            if ( JOptionPane.showConfirmDialog( 
                    this, bundle.getString( "ConfigureTestDependenciesDialog.btnRemoveActionPerformed.confirmMessage" ),
                    bundle.getString( "ConfigureTestDependenciesDialog.btnRemoveActionPerformed.confirmTitle" ),
                    JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_OPTION ) {
                
                int[] indices = listDependencies.getSelectedIndices();
                
                for ( int i = indices.length-1; i >= 0; i-- ) {
                    listDependenciesModel.remove( indices[i] );
                }
                
            }
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRemove;
    private javax.swing.JList<File> listDependencies;
    private javax.swing.JPanel panelDependencies;
    private javax.swing.JScrollPane scrollDependencies;
    // End of variables declaration//GEN-END:variables
}
