/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.jjudge.gui;

import br.com.davidbuzatto.jjudge.testsets.Student;
import br.com.davidbuzatto.jjudge.testsets.TestSet;
import br.com.davidbuzatto.jjudge.testsets.TestSetResult;
import br.com.davidbuzatto.jjudge.utils.Utils;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.DefaultCaret;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author David
 */
public class MainWindow extends javax.swing.JFrame {

    private DefaultListModel<File> listPackagesModel;
    private DefaultListModel<TestSet> listTestSetsModel;
    private List<TestSet> testSets;
    private int secondsToTimeout;
    private boolean outputStreams;
    
    /**
     * Creates new form JJudge
     */
    public MainWindow() {
        initComponents();
        customInit();
    }

    private void customInit() {
        
        secondsToTimeout = 10;
        outputStreams = false;
        
        setIconImage( new ImageIcon( getClass().getResource(
                "/br/com/davidbuzatto/jjudge/gui/icons/user_gray.png" ) ).getImage() );
        
        listPackagesModel = new DefaultListModel<>();
        listTestSetsModel = new DefaultListModel<>();
        
        listPackages.setModel( listPackagesModel );
        listTestSets.setModel( listTestSetsModel );
        
        lblStatus.setText( "" );
        
        DefaultCaret caret = (DefaultCaret) textPaneProcessOutput.getCaret();
        caret.setUpdatePolicy( DefaultCaret.ALWAYS_UPDATE );
        
        testSets = Utils.loadTestSets();
        buildTestSetsModel();
        
        menuTools.setVisible( false );
        
        //listPackagesModel.addElement( new File( "debugPackageC.zip" ) );
        //listPackagesModel.addElement( new File( "debugPackageCPP.zip" ) );
        //listPackagesModel.addElement( new File( "debugPackageJAVA.zip" ) );
        //listPackagesModel.addElement( new File( "debugPackagePYTHON.zip" ) );
        
    }
    
    private void buildTestSetsModel() {
        listTestSetsModel.clear();
        for ( TestSet ts : testSets ) {
            listTestSetsModel.addElement( ts );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemShowDetails = new javax.swing.JMenuItem();
        panelPackages = new javax.swing.JPanel();
        scrollPackages = new javax.swing.JScrollPane();
        listPackages = new javax.swing.JList<>();
        btnAddPackage = new javax.swing.JButton();
        btnRemovePackage = new javax.swing.JButton();
        panelTestSets = new javax.swing.JPanel();
        scrollTestSets = new javax.swing.JScrollPane();
        listTestSets = new javax.swing.JList<>();
        lblStatus = new javax.swing.JLabel();
        btnRunTest = new javax.swing.JButton();
        panelProcessOutput = new javax.swing.JPanel();
        scrollProcessOutput = new javax.swing.JScrollPane();
        textPaneProcessOutput = new javax.swing.JTextPane();
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemBuildTestPackage = new javax.swing.JMenuItem();
        sepMenuFile02 = new javax.swing.JPopupMenu.Separator();
        menuItemLoadTestSets = new javax.swing.JMenuItem();
        sepMenuFile01 = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuItemTestSets = new javax.swing.JMenuItem();
        menuTools = new javax.swing.JMenu();
        menuItemOptions = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemHowTo = new javax.swing.JMenuItem();
        sepMenuHelp01 = new javax.swing.JPopupMenu.Separator();
        menuItemAbout = new javax.swing.JMenuItem();

        menuItemShowDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/report.png"))); // NOI18N
        menuItemShowDetails.setText("Show details...");
        menuItemShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemShowDetailsActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemShowDetails);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JJudge");
        setResizable(false);

        panelPackages.setBorder(javax.swing.BorderFactory.createTitledBorder("Package(s) to Test"));

        scrollPackages.setViewportView(listPackages);

        btnAddPackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/add.png"))); // NOI18N
        btnAddPackage.setText("Add");
        btnAddPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPackageActionPerformed(evt);
            }
        });

        btnRemovePackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/delete.png"))); // NOI18N
        btnRemovePackage.setText("Remove");
        btnRemovePackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePackageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPackagesLayout = new javax.swing.GroupLayout(panelPackages);
        panelPackages.setLayout(panelPackagesLayout);
        panelPackagesLayout.setHorizontalGroup(
            panelPackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPackagesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPackagesLayout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(btnAddPackage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemovePackage)))
                .addContainerGap())
        );
        panelPackagesLayout.setVerticalGroup(
            panelPackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPackagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPackages, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPackagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemovePackage)
                    .addComponent(btnAddPackage))
                .addContainerGap())
        );

        panelTestSets.setBorder(javax.swing.BorderFactory.createTitledBorder("Test Set(s) (right click each item for details)"));

        listTestSets.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listTestSets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listTestSetsMousePressed(evt);
            }
        });
        scrollTestSets.setViewportView(listTestSets);

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(0, 102, 204));
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStatus.setText("status");

        btnRunTest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/accept.png"))); // NOI18N
        btnRunTest.setText("Run Test");
        btnRunTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTestSetsLayout = new javax.swing.GroupLayout(panelTestSets);
        panelTestSets.setLayout(panelTestSetsLayout);
        panelTestSetsLayout.setHorizontalGroup(
            panelTestSetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestSetsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTestSetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTestSets, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTestSetsLayout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRunTest)))
                .addContainerGap())
        );
        panelTestSetsLayout.setVerticalGroup(
            panelTestSetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTestSetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTestSets)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTestSetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRunTest)
                    .addComponent(lblStatus))
                .addContainerGap())
        );

        panelProcessOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Process Output"));

        textPaneProcessOutput.setEditable(false);
        textPaneProcessOutput.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        scrollProcessOutput.setViewportView(textPaneProcessOutput);

        javax.swing.GroupLayout panelProcessOutputLayout = new javax.swing.GroupLayout(panelProcessOutput);
        panelProcessOutput.setLayout(panelProcessOutputLayout);
        panelProcessOutputLayout.setHorizontalGroup(
            panelProcessOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProcessOutput)
                .addContainerGap())
        );
        panelProcessOutputLayout.setVerticalGroup(
            panelProcessOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProcessOutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollProcessOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuFile.setMnemonic('F');
        menuFile.setText("File");

        menuItemBuildTestPackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/package.png"))); // NOI18N
        menuItemBuildTestPackage.setMnemonic('B');
        menuItemBuildTestPackage.setText("Build Test Package");
        menuItemBuildTestPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuildTestPackageActionPerformed(evt);
            }
        });
        menuFile.add(menuItemBuildTestPackage);
        menuFile.add(sepMenuFile02);

        menuItemLoadTestSets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/database_refresh.png"))); // NOI18N
        menuItemLoadTestSets.setMnemonic('L');
        menuItemLoadTestSets.setText("Load Test Sets");
        menuItemLoadTestSets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadTestSetsActionPerformed(evt);
            }
        });
        menuFile.add(menuItemLoadTestSets);
        menuFile.add(sepMenuFile01);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/door_out.png"))); // NOI18N
        menuItemExit.setMnemonic('x');
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuFile.add(menuItemExit);

        menuBar.add(menuFile);

        menuEdit.setMnemonic('E');
        menuEdit.setText("Edit");

        menuItemTestSets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/database_edit.png"))); // NOI18N
        menuItemTestSets.setMnemonic('T');
        menuItemTestSets.setText("Test Sets");
        menuItemTestSets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTestSetsActionPerformed(evt);
            }
        });
        menuEdit.add(menuItemTestSets);

        menuBar.add(menuEdit);

        menuTools.setMnemonic('T');
        menuTools.setText("Tools");

        menuItemOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/wrench.png"))); // NOI18N
        menuItemOptions.setMnemonic('O');
        menuItemOptions.setText("Options");
        menuItemOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOptionsActionPerformed(evt);
            }
        });
        menuTools.add(menuItemOptions);

        menuBar.add(menuTools);

        menuHelp.setMnemonic('H');
        menuHelp.setText("Help");

        menuItemHowTo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/help.png"))); // NOI18N
        menuItemHowTo.setMnemonic('c');
        menuItemHowTo.setText("How to configure and use");
        menuItemHowTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHowToActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemHowTo);
        menuHelp.add(sepMenuHelp01);

        menuItemAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/davidbuzatto/jjudge/gui/icons/information.png"))); // NOI18N
        menuItemAbout.setMnemonic('A');
        menuItemAbout.setText("About...");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelProcessOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPackages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTestSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPackages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTestSets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelProcessOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPackageActionPerformed
        
        JFileChooser jfc = new JFileChooser( new File( Utils.getPref( "addPackagePath" ) ) );
        jfc.setDialogTitle( "Choose a package" );
        jfc.setMultiSelectionEnabled( true );
        jfc.setFileSelectionMode( JFileChooser.FILES_ONLY );
        jfc.removeChoosableFileFilter( jfc.getFileFilter() );
        jfc.setFileFilter( new FileNameExtensionFilter( "Zip file" , "zip" ) );
        
        jfc.showOpenDialog( this );
        File[] files = jfc.getSelectedFiles();
        
        if ( files != null && files.length > 0 ) {
            Utils.setPref( "addPackagePath", files[0].getParentFile().getAbsolutePath() );
            for ( File f : files ) {
                listPackagesModel.addElement( f );
            }
        }
        
    }//GEN-LAST:event_btnAddPackageActionPerformed

    private void btnRemovePackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePackageActionPerformed
        
        if ( listPackages.getSelectedValue() != null ) {
            
            if ( JOptionPane.showConfirmDialog( 
                    this, "Do you really want to remove the selected package?",
                    "Remove package",
                    JOptionPane.YES_NO_OPTION ) == JOptionPane.YES_OPTION ) {
                
                listPackagesModel.remove( listPackages.getSelectedIndex() );
                
            }
            
        }
        
    }//GEN-LAST:event_btnRemovePackageActionPerformed

    private void btnRunTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunTestActionPerformed
        
        TestSet tSet = listTestSets.getSelectedValue();
        List<TestSetResult> tSetResList = new ArrayList<>();
        
        if ( tSet != null && !listPackagesModel.isEmpty() ) {
            
            new Thread( new Runnable() {
                
                @Override
                public void run() {
                    
                    listPackages.setEnabled( false );
                    listTestSets.setEnabled( false );
                    btnAddPackage.setEnabled( false );
                    btnRemovePackage.setEnabled( false );
                    btnRunTest.setEnabled( false );
                    menuItemBuildTestPackage.setEnabled( false );
                    menuItemLoadTestSets.setEnabled( false );
                    menuItemExit.setEnabled( false );
                    menuItemTestSets.setEnabled( false );
                    menuItemOptions.setEnabled( false );
                    menuItemHowTo.setEnabled( false );
                    menuItemAbout.setEnabled( false );
                    lblStatus.setText( "Please wait while the tests are being executed." );
                    textPaneProcessOutput.setText( "" );
                    
                    try {
                        
                        for ( int i = 0; i < listPackagesModel.size(); i++ ) {
                            
                            File zipFile = listPackagesModel.get( i );
                            Utils.addFormattedText( 
                                    textPaneProcessOutput, 
                                    String.format( "Processing %s\n", zipFile ),
                                    Color.BLUE );
                            
                            tSetResList.add( Utils.runTest( 
                                    zipFile, 
                                    tSet, 
                                    outputStreams, 
                                    secondsToTimeout, 
                                    textPaneProcessOutput ) );
                            
                            Utils.addFormattedText( 
                                    textPaneProcessOutput, 
                                    String.format( "Cleaning up...\n\n", zipFile ),
                                    Color.BLACK );
                            
                            FileUtils.deleteDirectory( new File( zipFile.getAbsolutePath().replace( ".zip", "" ) ) );
                            
                        }
                        
                        //ResultDialog r = new ResultDialog( null, true, tSetResList );
                        //r.setVisible( true );
                        Utils.processResultsToExcel( tSetResList, tSet );
                        
                    } catch ( IOException | InterruptedException exc ) {
                        exc.printStackTrace();
                    }
                    
                    listPackages.setEnabled( true );
                    listTestSets.setEnabled( true );
                    btnAddPackage.setEnabled( true );
                    btnRemovePackage.setEnabled( true );
                    btnRunTest.setEnabled( true );
                    menuItemBuildTestPackage.setEnabled( true );
                    menuItemLoadTestSets.setEnabled( true );
                    menuItemExit.setEnabled( true );
                    menuItemTestSets.setEnabled( true );
                    menuItemOptions.setEnabled( true );
                    menuItemHowTo.setEnabled( true );
                    menuItemAbout.setEnabled( true );
                    lblStatus.setText( "Done!" );
                    
                }
                
            }).start();
            
        } else if ( tSet == null ) {
            JOptionPane.showMessageDialog( 
                    this, 
                    "You must select a Test Set!", 
                    "ERROR", JOptionPane.ERROR_MESSAGE );
        } else {
            JOptionPane.showMessageDialog( 
                    this, 
                    "You must have at least one package to test!", 
                    "ERROR", JOptionPane.ERROR_MESSAGE );
        }
        
    }//GEN-LAST:event_btnRunTestActionPerformed

    private void listTestSetsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTestSetsMousePressed
        
        if ( SwingUtilities.isRightMouseButton( evt ) ) {
            int index = listTestSets.locationToIndex( evt.getPoint() );
            if ( index != -1 ) {
                listTestSets.setSelectedIndex( index );
                listTestSets.requestFocus();
                popupMenu.show( listTestSets, evt.getX(), evt.getY() );
            }
        }
        
    }//GEN-LAST:event_listTestSetsMousePressed

    private void menuItemShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemShowDetailsActionPerformed
        
        TestSetDetailsDialog r = new TestSetDetailsDialog( 
                this, 
                true, 
                listTestSets.getSelectedValue() );
        r.setVisible( true );
        
    }//GEN-LAST:event_menuItemShowDetailsActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit( 0 );
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemTestSetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTestSetsActionPerformed
        
        EditTestSetsDialog etsd = new EditTestSetsDialog( this, true, testSets );
        etsd.setVisible( true );
        
        if ( etsd.getTestSets() != null ) {
            testSets = etsd.getTestSets();
            buildTestSetsModel();
        }
        
    }//GEN-LAST:event_menuItemTestSetsActionPerformed

    private void menuItemOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemOptionsActionPerformed

    private void menuItemHowToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHowToActionPerformed
        
        JOptionPane.showMessageDialog( 
                this, 
                "JJudge uses external tools for compilation and/or execution of\n"
              + "the tested programs.\n\n"
              + "To make it possible, it's necessary to modify the PATH\n"
              + "envinroment variable of your OS to point to the tools that are\n"
              + "necessary.\n\n"
              + "These tools are:\n"
              + "    GCC and G++ for C and C++ code;\n"
              + "    JDK for Java code;\n"
              + "    WinPython for Python code.\n\n"
              + "Note that you will need the appropriate version of the tool\n"
              + "based on the source code that will be compiled and tested.",
                "How to configure and use", 
                JOptionPane.INFORMATION_MESSAGE );
        
    }//GEN-LAST:event_menuItemHowToActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        JOptionPane.showMessageDialog( 
                this, 
                "JJudge is a Java desktop application that aims to automate\n"
              + "the checking of programs by compiling and executing them by\n"
              + "providing inputs and testing for expected outputs.\n\n"
              + "This tool was developed by Professor Dr. David Buzatto\n"
              + "for application in the disciplines in which he teaches.", 
                "About...", 
                JOptionPane.INFORMATION_MESSAGE );
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemLoadTestSetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadTestSetsActionPerformed
        
        JFileChooser jfc = new JFileChooser( new File( Utils.getPref( "loadTestSets" ) ) );
        jfc.setDialogTitle( "Choose a package of test sets" );
        jfc.setMultiSelectionEnabled( false );
        jfc.setFileSelectionMode( JFileChooser.FILES_ONLY );
        jfc.removeChoosableFileFilter( jfc.getFileFilter() );
        jfc.setFileFilter( new FileNameExtensionFilter( "Test Sets JSON File" , "json" ) );
        
        jfc.showOpenDialog( this );
        File file = jfc.getSelectedFile();
        
        if ( file != null ) {
            Utils.setPref( "loadTestSets", file.getParentFile().getAbsolutePath() );
            testSets = Utils.loadTestSets( file );
            buildTestSetsModel();
        }
        
    }//GEN-LAST:event_menuItemLoadTestSetsActionPerformed

    private void menuItemBuildTestPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuildTestPackageActionPerformed
        
        String name = JOptionPane.showInputDialog( "Student full name:" );
        String code;
        String packageName;
        
        if ( name != null ) {
            
            code = JOptionPane.showInputDialog( "Student code:" );
            
            if ( code != null ) {
                
                packageName = JOptionPane.showInputDialog( "Package name:" );
                
                if ( packageName != null ) {
                    
                    JFileChooser jfc = new JFileChooser( new File( Utils.getPref( "buildTestPackagePath" ) ) );
                    jfc.setDialogTitle( "Choose the files to insert into the test package" );
                    jfc.setMultiSelectionEnabled( true );
                    jfc.setFileSelectionMode( JFileChooser.FILES_ONLY );

                    jfc.showOpenDialog( this );
                    File[] files = jfc.getSelectedFiles();

                    if ( files != null && files.length > 0 ) {

                        String absolutePath = files[0].getParentFile().getAbsolutePath();
                        Utils.setPref( "buildTestPackagePath", absolutePath );
                        
                        Student s = new Student();
                        s.setName( name );
                        s.setCode( code );

                        try {
                            
                            File studentFile = new File( absolutePath + "/student.json" );
                            
                            Utils.saveStudent( s, studentFile );
                            
                            List<File> filesList = new ArrayList<>( Arrays.asList( files ) );
                            filesList.add( studentFile );
                            files = filesList.toArray( files );
                            
                            Utils.zipFiles( files, new File( absolutePath + "/" + packageName + ".zip" )  );
                            
                            studentFile.delete();
                            
                            JOptionPane.showMessageDialog( this, "The test package was built successfully!" );
                            
                        } catch ( IOException exc )  {
                            exc.printStackTrace();
                        }

                    }
                
                }
        
            }
            
        }
        
    }//GEN-LAST:event_menuItemBuildTestPackageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main( String args[] ) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals( info.getName() ) ) {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPackage;
    private javax.swing.JButton btnRemovePackage;
    private javax.swing.JButton btnRunTest;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList<File> listPackages;
    private javax.swing.JList<TestSet> listTestSets;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemBuildTestPackage;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemHowTo;
    private javax.swing.JMenuItem menuItemLoadTestSets;
    private javax.swing.JMenuItem menuItemOptions;
    private javax.swing.JMenuItem menuItemShowDetails;
    private javax.swing.JMenuItem menuItemTestSets;
    private javax.swing.JMenu menuTools;
    private javax.swing.JPanel panelPackages;
    private javax.swing.JPanel panelProcessOutput;
    private javax.swing.JPanel panelTestSets;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JScrollPane scrollPackages;
    private javax.swing.JScrollPane scrollProcessOutput;
    private javax.swing.JScrollPane scrollTestSets;
    private javax.swing.JPopupMenu.Separator sepMenuFile01;
    private javax.swing.JPopupMenu.Separator sepMenuFile02;
    private javax.swing.JPopupMenu.Separator sepMenuHelp01;
    private javax.swing.JTextPane textPaneProcessOutput;
    // End of variables declaration//GEN-END:variables
}
