package br.com.davidbuzatto.jjudge.gui;

import br.com.davidbuzatto.jjudge.plagiarism.PlagiarismTestResult;
import java.awt.Color;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Prof. Dr. David Buzatto
 */
public class PlagiarismDetectorResultFrame extends javax.swing.JFrame {
    
    private List<PlagiarismTestResult> results;
    private PlagiarismDetectorResultPanel pPanel;

    private boolean useLightTheme;
    
    /**
     * Creates new form PlagiarismDetectorResultFrame
     */
    public PlagiarismDetectorResultFrame( List<PlagiarismTestResult> results, Color plagiarismPanelBackgroundColor, boolean useLightTheme ) {
        
        this.useLightTheme = useLightTheme;
        
        this.results = results;
        initComponents();
        this.pPanel = (PlagiarismDetectorResultPanel) plagiarismPanel;
        updateSlider();
        
        this.pPanel.setBackgroundColor( plagiarismPanelBackgroundColor );
        setIconImage( new ImageIcon( getClass().getResource(
                "/br/com/davidbuzatto/jjudge/gui/icons/report.png" ) ).getImage() );
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        optionsPanel = new javax.swing.JPanel();
        lblMinimumSimilarityThreshold = new javax.swing.JLabel();
        sliderMinimumSimilarityThreshold = new javax.swing.JSlider();
        lblMinimumSimilarityThresholdValue = new javax.swing.JLabel();
        radioStudentName = new javax.swing.JRadioButton();
        radioStudentCode = new javax.swing.JRadioButton();
        scrollPaneResults = new javax.swing.JScrollPane();
        plagiarismPanel = new PlagiarismDetectorResultPanel( results, scrollPaneResults, useLightTheme );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/davidbuzatto/jjudge/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("PlagiarismDetectorResultPanel.title")); // NOI18N

        optionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("PlagiarismDetectorResultPanel.optionsPanel.title"))); // NOI18N

        lblMinimumSimilarityThreshold.setText(bundle.getString("PlagiarismDetectorResultPanel.lblMinimumSimilarityThreshold.text")); // NOI18N

        sliderMinimumSimilarityThreshold.setMaximum(1000);
        sliderMinimumSimilarityThreshold.setValue(0);
        sliderMinimumSimilarityThreshold.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderMinimumSimilarityThresholdStateChanged(evt);
            }
        });

        lblMinimumSimilarityThresholdValue.setText("0,00%");

        buttonGroup.add(radioStudentName);
        radioStudentName.setSelected(true);
        radioStudentName.setText(bundle.getString("PlagiarismDetectorResultPanel.radioStudentName.text")); // NOI18N
        radioStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStudentNameActionPerformed(evt);
            }
        });

        buttonGroup.add(radioStudentCode);
        radioStudentCode.setText(bundle.getString("PlagiarismDetectorResultPanel.radioStudentCode.text")); // NOI18N
        radioStudentCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioStudentCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMinimumSimilarityThreshold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderMinimumSimilarityThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMinimumSimilarityThresholdValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStudentName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioStudentCode)
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sliderMinimumSimilarityThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radioStudentName)
                        .addComponent(radioStudentCode)
                        .addComponent(lblMinimumSimilarityThresholdValue))
                    .addComponent(lblMinimumSimilarityThreshold))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plagiarismPanelLayout = new javax.swing.GroupLayout(plagiarismPanel);
        plagiarismPanel.setLayout(plagiarismPanelLayout);
        plagiarismPanelLayout.setHorizontalGroup(
            plagiarismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 756, Short.MAX_VALUE)
        );
        plagiarismPanelLayout.setVerticalGroup(
            plagiarismPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        scrollPaneResults.setViewportView(plagiarismPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneResults))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sliderMinimumSimilarityThresholdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderMinimumSimilarityThresholdStateChanged
        updateSlider();
        pPanel.setThreshold( getSliderPercentage() );
        pPanel.repaint();
    }//GEN-LAST:event_sliderMinimumSimilarityThresholdStateChanged

    private void radioStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStudentNameActionPerformed
        pPanel.setShowStudentName( radioStudentName.isSelected() );
        pPanel.repaint();
    }//GEN-LAST:event_radioStudentNameActionPerformed

    private void radioStudentCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioStudentCodeActionPerformed
        pPanel.setShowStudentName( radioStudentName.isSelected() );
        pPanel.repaint();
    }//GEN-LAST:event_radioStudentCodeActionPerformed

    private void updateSlider() {
        lblMinimumSimilarityThresholdValue.setText( String.format( "%.2f%%", getSliderPercentage() * 100 ) );
    }
    
    private double getSliderPercentage() {
        return sliderMinimumSimilarityThreshold.getValue() / (double) sliderMinimumSimilarityThreshold.getMaximum();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel lblMinimumSimilarityThreshold;
    private javax.swing.JLabel lblMinimumSimilarityThresholdValue;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JPanel plagiarismPanel;
    private javax.swing.JRadioButton radioStudentCode;
    private javax.swing.JRadioButton radioStudentName;
    private javax.swing.JScrollPane scrollPaneResults;
    private javax.swing.JSlider sliderMinimumSimilarityThreshold;
    // End of variables declaration//GEN-END:variables
}
