/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.davidbuzatto.jjudge.gui;

import br.com.davidbuzatto.jjudge.testsets.Test;
import br.com.davidbuzatto.jjudge.testsets.TestCase;
import br.com.davidbuzatto.jjudge.testsets.TestSet;
import br.com.davidbuzatto.jjudge.utils.Utils;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author David
 */
public class TestSetDetailsDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form ResultDialog
     */
    public TestSetDetailsDialog( JFrame parent, boolean modal, TestSet testSet ) {
        super( parent, modal );
        initComponents();
        customInit( testSet );
    }
    
    private void customInit( TestSet testSet ) {
        
        setIconImage( new ImageIcon( getClass().getResource(
                "/br/com/davidbuzatto/jjudge/gui/icons/report.png" ) ).getImage() );
        
        textAreaDetails.setText( processDetailsTestSet( testSet ) );
        
    }

    private String processDetailsTestSet( TestSet testSet ) {
        
        StringBuilder sb = new StringBuilder();
        
        sb.append( "Description: " ).append( testSet.getDescription() ).append( "\n" );
        sb.append( "Programming Language: " ).append( testSet.getProgrammingLanguage() ).append( "\n" );
        sb.append( "Tests:" ).append( "\n" );
        
        for ( Test t : testSet.getTests() ) {    
            
            sb.append( "|-- Name: " ).append( t.getName() ).append( "\n" );
            sb.append( "|   |-- file name: " ).append( t.getName() );
            
            switch ( testSet.getProgrammingLanguage() ) {
                case C:
                    sb.append( ".c" );
                    break;
                case CPP:
                    sb.append( ".cpp" );
                    break;
                case JAVA:
                    sb.append( ".java" );
                    break;
                case PYTHON:
                    sb.append( ".py" );
                    break;
                default:
                    sb.append( "<undefined>" );
                    break;
            }
            
            sb.append( "\n" );
            
            sb.append( "|   |-- test cases: " ).append( "\n" );
            
            int i = 1;
            for ( TestCase tc : t.getTestCases() ) {
                sb.append( String.format( "|   |   |-- test case %02d:\n", i++ ) );
                sb.append( "|   |   |   |-- input: " ).append( "\n" ).append( Utils.identText( tc.getInput(), 5 ) ).append( "\n" );
                sb.append( "|   |   |   |" ).append( "\n" );
                sb.append( "|   |   |   |-- output: " ).append( "\n" ).append( Utils.identText( tc.getOutput(), 5 ) ).append( "\n" );
                sb.append( "|   |   |   |" ).append( "\n" );
                sb.append( "|   |   |" ).append( "\n" );
            }
            
            sb.append( "|   |" ).append( "\n" );
            sb.append( "|" ).append( "\n" );
            
            
        }
        
        return sb.toString();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneDetails = new javax.swing.JScrollPane();
        textAreaDetails = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Test Set Details");

        textAreaDetails.setColumns(20);
        textAreaDetails.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        textAreaDetails.setRows(5);
        scrollPaneDetails.setViewportView(textAreaDetails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPaneDetails;
    private javax.swing.JTextArea textAreaDetails;
    // End of variables declaration//GEN-END:variables
}
